# Generated by Django 4.2.4 on 2023-09-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='years',
            new_name='year',
        ),
    ]
